### ISSUE TITLE
Dependency version for fringe-helper doesn't exist (anymore?)

### ISSUE THREAD

**Issue by behaghel** [nonsequitur/git-gutter-fringe-plus#2]
If you install from `list-packages`, it fails:
    package-compute-transaction: Need package `fringe-helper-20130519.1641', but only 20130519.741 is available

`fringe-helper` on Melpa:
http://melpa.milkbox.net/#/fringe-helper

I suspect Melpa has messed up with this version.

**Comment by bling** [comment]
luckily i had the existing version of fringe-helper, so i just committed that into my dotfiles, which of course resolves the problem.

**Comment by behaghel** [comment]
Thanks!
